/** @format */

export const NAVIGATION = {
  SCREENS: {
    ARTWORK_DETAILS: 'NAVIGATION.SCREENS.ARTWORK_DETAILS',
  },
  TAB: {
    HOME: 'NAVIGATION.TAB.HOME',
    FAVORITES: 'NAVIGATION.TAB.FAVORITES',
  },
  STACK: {
    HOME: 'NAVIGATION.STACK.HOME',
    FAVORITES: 'NAVIGATION.STACK.FAVORITES',
  },
};
